name: Java CI/CD
on: 
  push: 
    branches: master
    paths-ignore:
      - "Dhruv-Rajvanshi/java-quotes-app/.github/workflows/*"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-reusable-workflow:
    name: "Java CI/CD"
    uses: Dhruv-Rajvanshi/reusable_workflows/.github/workflows/java-ci-cd.yml@master
    with:
      # role-assume: "arn:aws:iam::410454990341:role/GitHubActionsRole"
      ECR_REPO: "java-new"
      TASK_DEFINITION: "java-app-task-definition"
      CONTAINER_NAME: "java-container"
      CLUSTER: "java-cluster"
      SERVICE: "java-service"
